### PR TITLE
replace 10_000 with 10, 000 and remove start_docker.sh

### PR DESCRIPTION
**Pull request by yuqisun**
As title.

### CODE REVIEW

**Comment by tancheng** [comment]
I think we'd better keep sync with tancheng/CGRA-Flow or the other way around, instead of pushing PRs on each side.

**Comment by yuqisun** [comment]
How about: All contribute to codedac repo, if you want to sync with tancheng repo can open a PR?

**Comment by tancheng** [comment]
Sounds great to me. However, there is no simple button to perform such sync. Now the coredac/CGRA-Flow is `This branch is 2 commits ahead of tancheng/CGRA-Flow:master` as shown in its profile, as it is forked while the tancheng/CGRA-Flow is the upstream, which means we need periodically make PR from coredac to tancheng.

But I think it is okay, so let's sync them now~

**Comment by tancheng** [comment]
Ah, I saw a button of `Contribute`, so it is simple :-)

**Comment by tancheng** [comment]
Done.

**Pull request merged**
